# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Whale
baseurl:        ""
url:            "http://iammisun.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Whale
  url:          http://iammisun.github.io
  email:          
  github:       iammisun
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/iammisun/iammisun.github.io
